### ISSUE TITLE
Emmet overrides any Vuetify-Sublime Completions

### ISSUE THREAD

**Issue by cb109** [vuetifyjs/vuetify-sublime#1]
# How to reproduce
- Install Vuetify-Sublime
- Install [Emmet-Sublime](https://github.com/sergeche/emmet-sublime)
- Try any of the documented snippets/completions

They won't work anymore, since Emmet seems to take over. Emmet's main feature is turning something like this:

```html
div.foo>ul.bar>li.baz*3
```
into that:
```html
<div class="foo">
  <ul class="bar">
    <li class="baz"></li>
    <li class="baz"></li>
    <li class="baz"></li>
  </ul>
</div>
```
It's pretty popular for web development and it would be great if they could be made to work side by side.

Cheers

**Comment by cb109** [comment]
Weird, I have that exact same build number :/ Ubuntu 17.10. Might be a different package interfering or some config. Good to know it's not a general problem. Will play around a bit with settings; if I find the culprit I'll let you know.

**Comment by abhaywawale** [comment]
I am Windows right now and closing this issue right now. Open another one if you find something.

**Comment by abhaywawale** [comment]
And don't worry. I am working on something for `v0.2.0` which may resolve your problem.
